[package]
name = "PigMaster"
version = "1.0.0"
authors = []

[addresses]
pig_master_addr = "0x17e082f3b25cd33058e5fdb13fda592a4d691e1a3c922f091431240d4a830795"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }

[dev-dependencies]
